[package]
name = "viter-python"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Python bindings for viter, the rusty forced aligner."
publish = false

[lib]
name = "_viter"
crate-type = ["cdylib"]

[dependencies]
viter-kaldi.workspace = true
viter-io.workspace = true
viter-train.workspace = true
viter-serve.workspace = true
viter-cli.workspace = true
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
toml = "1.1"
pyo3 = { version = "0.27.2", features = ["extension-module", "abi3-py39"] }
numpy = "0.27.1"
